# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
