# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160126_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(allow_unicode=True, max_length=300)),
                ('content', models.TextField()),
                ('publish_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
